### ISSUE TITLE
Store conversation pairings in database

### ISSUE THREAD

**Issue by patrickhpan** [Harvard-CS96/textroulette#15]
Save each pairing in database (not the content, just the fact that two people talked)

**Comment by jacoblurye** [comment]
Very basic functionality is up and running – we can store which session ids were paired and when. Storage of more substantive data (e.g., convo length, topic) to come.

**Comment by patrickhpan** [comment]
Haven't read code yet but I think you're storing id (socket id) not user_id (session id)
